name: CI

on:
  push:
    branches: ['main']

jobs:
  test:
    name: test ${{ matrix.os }} / ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        os: ubuntu
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        include:
          # no pydantic-core binaries for pypy on windows, so tests take absolute ages
          # macos tests with pypy take ages (>10mins) since pypy is very slow
          # so we only test pypy on ubuntu
          - os: ubuntu
            python-version: 'pypy3.7'
          - os: ubuntu
            python-version: 'pypy3.8'
          - os: ubuntu
            python-version: 'pypy3.9'

    env:
      PYTHON: ${{ matrix.python-version }}
      OS: ${{ matrix.os }}

    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v3

    - uses: pdm-project/setup-pdm@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: install deps
      run: |
        pdm use -f $PYTHON
        pdm install -G testing

    - run: pdm info && pdm list

    - name: Test
      run: pdm run pytest

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3